"""
Abstract base agent for all compliance domain agents.
Uses LiteLLM for LLM calls - swap config for POC 0 (Ollama) vs POC 1 (Azure OpenAI).
All agents are fully async using asyncio.
"""
from __future__ import annotations
import time
from abc import ABC, abstractmethod
from typing import Any
import litellm
from config.settings import get_settings
from config.logging_config import get_logger
from models.review_result import (
    ComplianceDomain,
        DomainReviewResult,
            ComplianceFinding,
                Severity,
                    CitationSource,
                    )

                    logger = get_logger(__name__)


                    class BaseComplianceAgent(ABC):
                        """
                            Abstract base for all compliance domain agents.

                                Each domain agent (Brand, Legal, Accessibility, etc.) inherits this class.
                                    The LLM call is handled here via LiteLLM - agents only define their domain
                                        prompt and parsing logic.

                                            POC 0: LLM_MODEL=ollama/llama3 (local, zero cost)
                                                POC 1: LLM_MODEL=azure/gpt-4o-mini (Azure, minimal cost)
                                                    No code changes required between phases.
                                                        """

                                                            def __init__(self) -> None:
                                                                    self.settings = get_settings()
                                                                            self.logger = get_logger(self.__class__.__name__)

                                                                                @property
                                                                                    @abstractmethod
                                                                                        def domain(self) -> ComplianceDomain:
                                                                                                """The compliance domain this agent handles."""
                                                                                                        ...
                                                                                                        
                                                                                                            @property
                                                                                                                @abstractmethod
                                                                                                                    def system_prompt(self) -> str:
                                                                                                                            """Domain-specific system prompt grounding the agent's review scope."""
                                                                                                                                    ...
                                                                                                                                    
                                                                                                                                        @abstractmethod
                                                                                                                                            def build_review_prompt(
                                                                                                                                                    self,
                                                                                                                                                            asset_content: str,
                                                                                                                                                                    retrieved_context: str,
                                                                                                                                                                            asset_metadata: dict[str, Any],
                                                                                                                                                                                ) -> str:
                                                                                                                                                                                        """Build the grounded review prompt with retrieved compliance guidance."""
                                                                                                                                                                                                ...
                                                                                                                                                                                                
                                                                                                                                                                                                    @abstractmethod
                                                                                                                                                                                                        def parse_llm_response(
                                                                                                                                                                                                                self,
                                                                                                                                                                                                                        response_text: str,
                                                                                                                                                                                                                                asset_id: str,
                                                                                                                                                                                                                                    ) -> DomainReviewResult:
                                                                                                                                                                                                                                            """Parse LLM response into structured DomainReviewResult."""
                                                                                                                                                                                                                                                    ...
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                        async def review(
                                                                                                                                                                                                                                                                self,
                                                                                                                                                                                                                                                                        asset_id: str,
                                                                                                                                                                                                                                                                                asset_content: str,
                                                                                                                                                                                                                                                                                        retrieved_context: str,
                                                                                                                                                                                                                                                                                                asset_metadata: dict[str, Any] | None = None,
                                                                                                                                                                                                                                                                                                    ) -> DomainReviewResult:
                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                    Run compliance review for this domain.
                                                                                                                                                                                                                                                                                                                            Called by OrchestratorAgent via asyncio.gather() for parallel execution.
                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                            start_time = time.monotonic()
                                                                                                                                                                                                                                                                                                                                                    metadata = asset_metadata or {}
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                            self.logger.info(
                                                                                                                                                                                                                                                                                                                                                                        "starting_domain_review",
                                                                                                                                                                                                                                                                                                                                                                                    domain=self.domain.value,
                                                                                                                                                                                                                                                                                                                                                                                                asset_id=asset_id,
                                                                                                                                                                                                                                                                                                                                                                                                            model=self.settings.llm_model,
                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                                                                                                                        prompt = self.build_review_prompt(asset_content, retrieved_context, metadata)
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                    # LiteLLM call - works with Ollama (POC 0) and Azure OpenAI (POC 1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Only the LLM_MODEL env var changes between phases
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            response = await litellm.acompletion(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            model=self.settings.llm_model,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            messages=[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {"role": "system", "content": self.system_prompt},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {"role": "user", "content": prompt},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    temperature=self.settings.llm_temperature,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    max_tokens=self.settings.llm_max_tokens,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    api_base=self.settings.llm_base_url if "ollama" in self.settings.llm_model else None,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            response_text = response.choices[0].message.content or ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        duration_ms = int((time.monotonic() - start_time) * 1000)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    result = self.parse_llm_response(response_text, asset_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                result.review_duration_ms = duration_ms
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            result.agent_model = self.settings.llm_model
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.logger.info(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "domain_review_complete",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        domain=self.domain.value,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        asset_id=asset_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        passed=result.passed,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        severity=result.overall_severity.value,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        findings=result.finding_count,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        duration_ms=duration_ms,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return result
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as exc:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    duration_ms = int((time.monotonic() - start_time) * 1000)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.logger.error(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "domain_review_failed",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                domain=self.domain.value,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                asset_id=asset_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                error=str(exc),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                duration_ms=duration_ms,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Return a failed result with escalation rather than crashing orchestrator
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return DomainReviewResult(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    domain=self.domain,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    asset_id=asset_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    passed=False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    overall_severity=Severity.HIGH,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    findings=[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ComplianceFinding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rule="agent_error",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        description=f"Agent failed to complete review: {str(exc)}",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                severity=Severity.HIGH,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        passed=False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rationale="Review agent encountered an error and could not complete assessment.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        citations=[],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            summary=f"Review failed due to agent error: {str(exc)}",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            requires_human_review=True,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            escalation_reason=f"Agent error in {self.domain.value}: {str(exc)}",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            agent_model=self.settings.llm_model,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            review_duration_ms=duration_ms,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
