"""
Product Marketing Compliance Agent.
Reviews creative assets against Microsoft Product Marketing Standards.
Checks: feature accuracy, messaging alignment, campaign standards, product naming.
"""
from __future__ import annotations
import json
from typing import Any
from agents.base_agent import BaseComplianceAgent
from models.review_result import (
    ComplianceDomain,
        DomainReviewResult,
            ComplianceFinding,
                Severity,
                )

                PRODUCT_MARKETING_SYSTEM_PROMPT = """You are a Microsoft Product Marketing Compliance Reviewer.
                Your role is to evaluate creative assets against Microsoft Product Marketing Standards.

                You review for:
                - Correct product names and capitalization (e.g. "Microsoft 365" not "Office 365")
                - Accurate feature descriptions (no promises of unreleased features)
                - Pricing accuracy and currency consistency
                - Campaign message alignment with approved messaging framework
                - Correct use of product screenshots and UI elements
                - Competitive claim accuracy and substantiation
                - Call-to-action clarity and accuracy
                - Offer terms completeness

                Respond in JSON format with the same structure as other agents."""


                class ProductMarketingAgent(BaseComplianceAgent):
                    """Product Marketing compliance domain agent."""

                        @property
                            def domain(self) -> ComplianceDomain:
                                    return ComplianceDomain.PRODUCT_MARKETING

                                        @property
                                            def system_prompt(self) -> str:
                                                    return PRODUCT_MARKETING_SYSTEM_PROMPT

                                                        def build_review_prompt(
                                                                self,
                                                                        asset_content: str,
                                                                                retrieved_context: str,
                                                                                        asset_metadata: dict[str, Any],
                                                                                            ) -> str:
                                                                                                    filename = asset_metadata.get("filename", "unknown")
                                                                                                            campaign = asset_metadata.get("campaign", "Unknown Campaign")
                                                                                                                    return f"""Review this creative asset for Microsoft Product Marketing compliance.
                                                                                                                    
                                                                                                                    ASSET: {filename} | CAMPAIGN: {campaign}
                                                                                                                    METADATA: {json.dumps(asset_metadata, indent=2)}
                                                                                                                    
                                                                                                                    CONTENT:
                                                                                                                    {asset_content[:3000]}
                                                                                                                    
                                                                                                                    PRODUCT MARKETING GUIDANCE (cite ONLY these sources):
                                                                                                                    {retrieved_context}
                                                                                                                    
                                                                                                                    Verify all product names, feature claims, and pricing against the guidance.
                                                                                                                    Flag incorrect product names as MEDIUM severity.
                                                                                                                    Flag inaccurate feature claims as HIGH severity."""
                                                                                                                    
                                                                                                                        def parse_llm_response(self, response_text: str, asset_id: str) -> DomainReviewResult:
                                                                                                                                try:
                                                                                                                                            text = response_text.strip()
                                                                                                                                                        if "```json" in text:
                                                                                                                                                                        text = text.split("```json")[1].split("```")[0].strip()
                                                                                                                                                                                    elif "```" in text:
                                                                                                                                                                                                    text = text.split("```")[1].split("```")[0].strip()
                                                                                                                                                                                                    
                                                                                                                                                                                                                data = json.loads(text)
                                                                                                                                                                                                                            findings = [
                                                                                                                                                                                                                                            ComplianceFinding(
                                                                                                                                                                                                                                                                rule=f.get("rule", "unknown"),
                                                                                                                                                                                                                                                                                    description=f.get("description", ""),
                                                                                                                                                                                                                                                                                                        severity=Severity(f.get("severity", "medium")),
                                                                                                                                                                                                                                                                                                                            passed=f.get("passed", False),
                                                                                                                                                                                                                                                                                                                                                rationale=f.get("rationale", ""),
                                                                                                                                                                                                                                                                                                                                                                    suggested_fix=f.get("suggested_fix"),
                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                    for f in data.get("findings", [])
                                                                                                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                                                                                                            return DomainReviewResult(
                                                                                                                                                                                                                                                                                                                                                                                                                                            domain=self.domain,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            asset_id=asset_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            passed=data.get("passed", False),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            overall_severity=Severity(data.get("overall_severity", "medium")),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            findings=findings,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            summary=data.get("summary", "Product marketing review completed."),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            agent_model=self.settings.llm_model,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except (json.JSONDecodeError, KeyError, ValueError) as exc:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.logger.warning("product_marketing_agent_parse_error", error=str(exc))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return DomainReviewResult(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        domain=self.domain,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        asset_id=asset_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        passed=False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        overall_severity=Severity.MEDIUM,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        findings=[],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        summary=f"Product marketing review parse failed: {str(exc)}",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        requires_human_review=True,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        escalation_reason="Product marketing agent parse error",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        agent_model=self.settings.llm_model,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
